source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0.4'
pod 'Mantle', '~>2.0'
pod 'YYKit', '~> 1.0.5'
pod 'MJRefresh_Bell', '~> 3.1.0.1'
pod 'FDFullscreenPopGesture', '1.1'
pod 'MagicalRecord', '~> 2.3.2'
pod 'ReactiveCocoa','2.5'
pod 'UITableView+FDTemplateLayoutCell'
